spring.datasource.url=jdbc:postgresql://localhost:5432/shape_puzzles
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=klocek-nie-pasuje-ale-gracz-i-tak-twierdzi-ze-rozwiazal